### ISSUE TITLE
unique_x_points seems not to be linear

### ISSUE THREAD

**Issue by tomaszgawron901** [deemozyc/convex_hull_exercise#4]
I created a test to check if unique_x_points has linear time complexity and it seems like it does **not**. 
Tested on parabolic test set. [test code](https://github.com/tomaszgawron901/convex_hull_exercise/blob/unique_x_points_test/unique_test.cpp)

---
Reults

| no. points | time to run |
|--------|--------|
| 2^2 | 0.000009 |
| 2^3 | 0.000005 |
| 2^4 | 0.000012 |
| 2^5 | 0.00002 |
| 2^6 | 0.000043 |
| 2^7 | 0.000109 |
| 2^8 | 0.000175 |
| 2^9 | 0.00053 |
| 2^10 | 0.00127 |
| 2^11 | 0.004848 |
| 2^12 | 0.014947 |
| 2^13 | 0.053351 |
| 2^14 | 0.136846 |
| 2^15 | 0.641654 |
| 2^16 | 1.392598 |
| 2^17 | 2.486823 |
| 2^18 | 2.708825 |
| 2^19 | 5.441405 |
| 2^20 | 17.973759 |
| 2^21 | 69.3584 |
| 2^22 | 438.342322 |

![image](https://github.com/deemozyc/convex_hull_exercise/assets/49018724/4742ca2e-44a6-4dd4-8fa6-a618f2aecbae)

**Comment by deemozyc** [comment]
the time complexity of this function is linear in theoretical and it's a right implement, I think. 
This issue seems more about computer engineering. e.g. when the size of data in memory reachs CPU L1/L2/L3 cache size, there will be a performance "gap". 
I will do some optimise on this later, but we cannot expect much more.

**Comment by deemozyc** [comment]
> the time complexity of this function is linear in theoretical and it's a right implement, I think. This issue seems more about computer engineering. e.g. when the size of data in memory reachs CPU L1/L2/L3 cache size, there will be a performance "gap". I will do some optimise on this later, but we cannot expect much more.
linear in theoretical on random data
