### ISSUE TITLE
invalid test case

### ISSUE THREAD

**Issue by tomaszgawron901** [deemozyc/convex_hull_exercise#5]
I found a test case on which our algorithm fails to compute convex hull.
![image](https://github.com/deemozyc/convex_hull_exercise/assets/49018724/8f808f45-9afe-4055-9638-8b1c707c0dd3)
You can find test case data there:[convex_in_2.txt](https://github.com/deemozyc/convex_hull_exercise/files/13465449/convex_in_2.txt)

As you can see all points have unique x coordinates so it is like running it with `unique_x_points`.
Be aware that in order to recreate the bug you need to run MBC **without** `unique_x_points` as it changes the order of points. The order in which constraints are applied in LP is important in this bug.

This bug is also related to this problem:
![image](https://github.com/deemozyc/convex_hull_exercise/assets/49018724/b1c0497d-418e-4ea9-a7c0-a7c8172d25d4)

**Comment by deemozyc** [comment]
I will look into that. I also found an invalid test case last night. And it depends on the order of points, too

**Comment by deemozyc** [comment]
I found that the two invalid test cases are both caused by c_1d==0.
But I am not sure how to deal with c_1d==0. The optimal answer to it can be anything.
I tried to deal with it as unbounded or some others. But none of these ways works well in the two cases. one passed another failed.
